import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Lower Name Surname",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-dvh overflow-y-auto snap-y snap-mandatory scroll-smooth">
      <body
        className={`${inter.variable} antialiased bg-gray-md`}
      >
        <Header/>
        {children}

      </body>
    </html>
  );
}
